config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/' => 'welcome#index'

  get '/404'          => 'pages#not_found'
  # get '/about'        => 'pages#show_slug', slug: 'about'
  # get '/about/people' => 'pages#show_slug', slug: 'about_people'
  get '/tos'          => 'pages#show_slug', slug: 'tos',     as: :tos_page
  get '/privacy'      => 'pages#show_slug', slug: 'privacy', as: :privacy_page
  # get '/leadership'   => 'pages#leadership'
  get '/forthcoming'  => 'pages#forthcoming'

  get '/search' => 'search#index'

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  resources :downloads, only: [:show] do
    member do
      get :preview
    end
  end
  get '/downloads/:id/pdf_proxy(/:s3)',
      as: :pdf_proxy_download, to: 'downloads#pdf_proxy', constraints: { s3: %r{[^\/]+} }
  get '/downloads/content_guides/:id(/:slug)', as: :content_guide_pdf, to: 'content_guides#show_pdf'
  resources :explore_curriculum, only: %i(index show)
  resources :enhance_instruction, only: :index
  resources :find_lessons, only: :index
  resources :pages, only: :show
  resources :resources, only: :show do
    get :pdf_proxy, on: :collection, path: 'pdf-proxy'
  end
  resource :survey, only: %i(create show)

  get '/resources/:id/related_instruction' => 'resources#related_instruction', as: :related_instruction
  get '/media/:id' => 'resources#media', as: :media
  get '/other/:id' => 'resources#generic', as: :generic
  get '/content_guides/:id(/:slug)', as: :content_guide, to: 'content_guides#show'

  resources :documents, only: :show do
    member do
      post 'export', to: 'documents#export'
      get 'export/status', to: 'documents#export_status'
      post 'lti', to: 'documents#show_lti'
    end
  end
  resources :materials, only: :show do
    member do
      get 'preview/pdf', to: 'materials#preview_pdf'
      get 'preview/gdoc', to: 'materials#preview_gdoc'
    end
  end

  devise_for :users, class_name: 'User', controllers: { registrations: 'registrations', sessions: 'sessions' }

  authenticate :user do
    mount Resque::Server, at: '/queue'
  end

  namespace :admin do
    get '/' => 'welcome#index'
    get 'google_oauth2_callback' => 'google_oauth2#callback'
    get '/association_picker' => 'association_picker#index'
    resources :content_guide_definitions, only: %i(index new) do
      get :import, on: :collection
    end
    resources :content_guides, except: :create do
      collection do
        get :import
        get :links_validation
        post :reset_pdfs
      end
    end
    resources :reading_assignment_texts
    resource :resource_bulk_edits, only: %i(new create)
    get '/resource_picker' => 'resource_picker#index'
    resources :resources, except: :show do
      member do
        post :export_to_lti_cc, path: 'export-lti-cc'
        post :unit_bundle
      end
    end
    resources :download_categories, except: :show
    resources :pages, except: :show
    resources :settings, only: [] do
      patch :toggle_editing_enabled, on: :collection
    end
    resources :staff_members, except: :show
    resources :users, except: :show do
      post :reset_password, on: :member
    end
    resources :leadership_posts, except: :show
    resources :content_guide_faqs, except: :show
    resources :standards, only: %i(index edit update)

    resources :components, only: %i(index show)
    resource :sketch_compiler, path: 'sketch-compiler', only: [] do
      get '/', to: 'sketch_compilers#new', defaults: { version: 'v1' }
      get '/:version/new', to: 'sketch_compilers#new', as: :new
      post '/:version/compile', to: 'sketch_compilers#compile', as: :compile
    end
    resources :documents, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'documents#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'documents#import_status'
      end
    end
    resources :materials, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'materials#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'materials#import_status'
      end
    end
    resources :documents, only: %i(index create new destroy)
    resources :materials, only: %i(index create new destroy)
    resource :curriculum, only: %i(edit update)
    resources :access_codes
    resource :batch_reimport, only: %i(new create)
  end

  get '/*slug' => 'resources#show', as: :show_with_slug
end

app/models/standard.rb
# frozen_string_literal: true

class Standard < ActiveRecord::Base
  ALT_NAME_REGEX = {
    'ela' => /^[[:alpha:]]+\.(k|pk|\d+)\.\d+(\.[[:alnum:]]+)?$/,
    'math' => /^(k|pk|\d+)\.[[:alpha:]]+(\.[[:alpha:]]+)?\.\d+(\.[[:alpha:]]+)?$/
  }.freeze

  validates_presence_of :subject

  mount_uploader :language_progression_file, LanguageProgressionFileUploader

  has_many :content_guide_standards, dependent: :destroy
  has_many :content_guides, through: :content_guide_standards

  has_many :resource_standards
  has_many :resources, through: :resource_standards

  has_many :standard_emphases, class_name: 'StandardEmphasis', dependent: :destroy

  scope :bilingual, -> { where(is_language_progression_standard: true) }

  scope :by_grade, ->(grade) { by_grades [grade] }
  scope :by_grades, lambda { |grades|
    joins(resource_standards: { resource: [:grades] })
      .where('grades.id' => grades.map(&:id))
  }

  scope :ela, -> { where(subject: 'ela') }
  scope :math, -> { where(subject: 'math') }

  def self.search_by_name(name)
    where('name ILIKE :q OR alt_names::text ILIKE :q', q: "%#{name}%").order(:id)
  end

  def self.filter_ccss_standards(name, subject)
    name =~ ALT_NAME_REGEX[subject] ? name.upcase : nil
  end

  def attachment_url
    language_progression_file.url if language_progression_file.present?
  end

  def short_name
    alt_names.map { |n| self.class.filter_ccss_standards(n, subject) }.compact.try(:first) || name
  end

  def emphasis(grade = nil)
    # if we have a grade, grab first the emphasis for the corresponding grade,
    # if it doesn't exists then grab the general emphasis (with grade = nil)
    if grade.present?
      standard_emphases.where(grade: [grade, nil]).order(:grade).first.try(:emphasis)
    else
      standard_emphases.first.try(:emphasis)
    end
  end
end

app/controllers/admin/standards_controller.rb
module Admin
  class StandardsController < AdminController
    before_action :find_standard, except: [:index]

    def index
      @query = OpenStruct.new params[:query]

      scope = Standard.order(:id)
      scope = Standard.bilingual if @query.is_language_progression_standard == '1'
      scope = scope.search_by_name(@query.name) if @query.name.present?

      @standards = scope.paginate(page: params[:page])
    end

    def update
      if @standard.update(standard_params)
        redirect_to admin_standards_path, notice: t('.success')
      else
        render :edit
      end
    end

    private

    def find_standard
      @standard = Standard.find(params[:id])
    end

    def standard_params
      @std_params ||= params.require(:standard).permit(
        :description,
        :language_progression_note,
        :language_progression_file,
        :language_progression_file_cache,
        :remove_language_progression_file
      ).tap do |whitelist|
        ps = params[:standard]

        whitelist[:is_language_progression_standard] = true if ps[:language_progression_file].present?
        whitelist[:is_language_progression_standard] = false if ps[:remove_language_progression_file] == '1'
      end
    end
  end
end

app/views/admin/standards/_form.html.erb
<%= simple_form_for @standard, as: :standard, url: admin_standard_path(@standard), html: { class: 'o-standard-form' } do |f| %>

  <div class="row o-admin-standard-readonly">
    <label>Name: </label>
    <span><%= @standard.name %></span>
  </div>

  <div class="row o-admin-standard-readonly">
    <label class="col-md-4">Synonyms: </label>
    <div class="col-md-8"><%= @standard.alt_names.join(' | ') %></div>
  </div>

  <%= f.input :description, as: :ckeditor, input_html: { rows: 5 } %>

  <% if f.object.language_progression_file.url %>
    <div class="o-standard-form-current-file">
      <%= f.label :current_image %>
      <img src="<%= f.object.language_progression_file.url %>" />
    </div>
    <label><%= f.check_box :remove_language_progression_file %> Remove file</label>
  <% end %>

  <%= f.input :language_progression_file, as: :file %>
  <%= f.input :language_progression_file_cache, as: :hidden %>

  <%= f.input :language_progression_note, as: :ckeditor, input_html: { rows: 2 } %>

  <%= f.button :submit, t('ui.save'), name: nil %>
<% end %>

app/views/admin/standards/_search_form.html.erb
<%= simple_form_for :query, url: :admin_standards, html: { class: 'form-inline well o-admin-standards-search', method: :get } do |f| %>

  <div class='row align-bottom align-justify'>
    <%= f.input :name, label: 'Name', required: false, wrapper_html: { class: 'resource-search-title' } %>
    <%= f.input :is_language_progression_standard, label: 'Only Language Progression Standards', as: :boolean, required: false %>
    <%= f.button :submit, t('ui.search'), class: 'resource-search-button', name: nil %>
  </div>

<% end %>

app/views/admin/standards/edit.html.erb
<% title = t('.page_title') %>

<% set_page_title title %>

<div class=o-page>
  <h2 class=text-center><%= title %></h2>

  <%= render 'form' %>
</div>

app/views/admin/standards/index.html.erb
<div class=o-page>

  <h2 class=text-center>Standards</h2>

  <%= render 'search_form' %>

  <div class=row>
    <div class="col-md-12 o-admin-standards-table">
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Type</th>
          <th>Subject</th>
          <th>Grades</th>
          <th>Synonyms</th>
          <th>Action</th>
        </tr>

        <% @standards.each do |std| %>
          <tr id="std<%= std.id %>">
            <td><b><%= std.name %></b></td>
            <td><%= std.type %></td>
            <td><%= std.subject %></td>
            <td><%= std.grades.join(', ') %></td>
            <td><%= std.alt_names.join(' / ') %></td>
            <td><%= link_to 'edit', edit_admin_standard_path(std), class: 'button btn o-btn' %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class='col-sm-12 text-center'>
      <%= will_paginate @standards, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>