config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/' => 'welcome#index'

  get '/404'          => 'pages#not_found'
  # get '/about'        => 'pages#show_slug', slug: 'about'
  # get '/about/people' => 'pages#show_slug', slug: 'about_people'
  get '/tos'          => 'pages#show_slug', slug: 'tos',     as: :tos_page
  get '/privacy'      => 'pages#show_slug', slug: 'privacy', as: :privacy_page
  # get '/leadership'   => 'pages#leadership'
  get '/forthcoming'  => 'pages#forthcoming'

  get '/search' => 'search#index'

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  resources :downloads, only: [:show] do
    member do
      get :preview
    end
  end
  get '/downloads/:id/pdf_proxy(/:s3)',
      as: :pdf_proxy_download, to: 'downloads#pdf_proxy', constraints: { s3: %r{[^\/]+} }
  get '/downloads/content_guides/:id(/:slug)', as: :content_guide_pdf, to: 'content_guides#show_pdf'
  resources :explore_curriculum, only: %i(index show)
  resources :enhance_instruction, only: :index
  resources :find_lessons, only: :index
  resources :pages, only: :show
  resources :resources, only: :show do
    get :pdf_proxy, on: :collection, path: 'pdf-proxy'
  end
  resource :survey, only: %i(create show)

  get '/resources/:id/related_instruction' => 'resources#related_instruction', as: :related_instruction
  get '/media/:id' => 'resources#media', as: :media
  get '/other/:id' => 'resources#generic', as: :generic
  get '/content_guides/:id(/:slug)', as: :content_guide, to: 'content_guides#show'

  resources :documents, only: :show do
    member do
      post 'export', to: 'documents#export'
      get 'export/status', to: 'documents#export_status'
      post 'lti', to: 'documents#show_lti'
    end
  end
  resources :materials, only: :show do
    member do
      get 'preview/pdf', to: 'materials#preview_pdf'
      get 'preview/gdoc', to: 'materials#preview_gdoc'
    end
  end

  devise_for :users, class_name: 'User', controllers: { registrations: 'registrations', sessions: 'sessions' }

  authenticate :user do
    mount Resque::Server, at: '/queue'
  end

  namespace :admin do
    get '/' => 'welcome#index'
    get 'google_oauth2_callback' => 'google_oauth2#callback'
    get '/association_picker' => 'association_picker#index'
    resources :content_guide_definitions, only: %i(index new) do
      get :import, on: :collection
    end
    resources :content_guides, except: :create do
      collection do
        get :import
        get :links_validation
        post :reset_pdfs
      end
    end
    resources :reading_assignment_texts
    resource :resource_bulk_edits, only: %i(new create)
    get '/resource_picker' => 'resource_picker#index'
    resources :resources, except: :show do
      member do
        post :export_to_lti_cc, path: 'export-lti-cc'
        post :unit_bundle
      end
    end
    resources :download_categories, except: :show
    resources :pages, except: :show
    resources :settings, only: [] do
      patch :toggle_editing_enabled, on: :collection
    end
    resources :staff_members, except: :show
    resources :users, except: :show do
      post :reset_password, on: :member
    end
    resources :leadership_posts, except: :show
    resources :content_guide_faqs, except: :show
    resources :standards, only: %i(index edit update)

    resources :components, only: %i(index show)
    resource :sketch_compiler, path: 'sketch-compiler', only: [] do
      get '/', to: 'sketch_compilers#new', defaults: { version: 'v1' }
      get '/:version/new', to: 'sketch_compilers#new', as: :new
      post '/:version/compile', to: 'sketch_compilers#compile', as: :compile
    end
    resources :documents, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'documents#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'documents#import_status'
      end
    end
    resources :materials, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'materials#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'materials#import_status'
      end
    end
    resources :documents, only: %i(index create new destroy)
    resources :materials, only: %i(index create new destroy)
    resource :curriculum, only: %i(edit update)
    resources :access_codes
    resource :batch_reimport, only: %i(new create)
  end

  get '/*slug' => 'resources#show', as: :show_with_slug
end

app/models/content_guide.rb
# frozen_string_literal: true

require 'google/apis/drive_v3'

class ContentGuide < ActiveRecord::Base
  include Searchable
  include PDFDownloadable

  ICON_VALUES = %w(complexity instruction volume).freeze

  attr_accessor :update_metadata, :faq

  acts_as_taggable_on :grades

  has_many :content_guide_standards
  has_many :common_core_standards, -> { where(type: 'CommonCoreStandard') },
           source: :standard, through: :content_guide_standards
  has_many :resources, through: :unbounded_standards
  has_many :standards, through: :content_guide_standards
  has_many :unbounded_standards, -> { where(type: 'UnboundedStandard') },
           source: :standard, through: :content_guide_standards

  has_many :social_thumbnails, as: :target

  validates :date, :description, :subject, :teaser, :title, presence: true, if: :validate_metadata?
  validates :permalink, format: { with: /\A\w+\z/ }, uniqueness: { case_sensitive: false }
  validate :icon_values
  validate :media_exist
  validate :no_broken_ext_links
  validate :no_broken_internal_links

  before_validation :process_content, unless: :update_metadata
  before_validation :downcase_permalink
  before_save :set_slug

  mount_uploader :big_photo, ContentGuidePhotoUploader
  mount_uploader :pdf, ContentGuidePdfUploader
  mount_uploader :small_photo, ContentGuidePhotoUploader

  scope :where_subject, lambda { |subjects|
    subjects = Array.wrap(subjects)
    subjects.any? ? where(subject: subjects) : where(nil)
  }

  scope :where_grade, lambda { |value|
    value = Array.wrap(value)
    return where(nil) unless value.any?

    joins(taggings: [:tag])
      .where(taggings: { context: 'grades' })
      .where(tags: { name: value })
  }

  delegate :broken_ext_links, :tasks_without_break, to: :presenter

  class << self
    def file_id_from_url(url)
      url.scan(/\/d\/([^\/]+)\/?/).first.first rescue nil
    end

    def import(file_id, credentials)
      service = Google::Apis::DriveV3::DriveService.new
      service.authorization = credentials

      file = service.get_file(file_id, fields: 'lastModifyingUser,modifiedTime,name,version')
      content = service.export_file(file_id, 'text/html').encode('ASCII-8BIT').force_encoding('UTF-8')

      cg = find_or_initialize_by(file_id: file_id)
      cg.attributes = {
        name: file.name,
        last_modified_at: file.modified_time,
        last_modifying_user_email: file.last_modifying_user.email_address,
        last_modifying_user_name: file.last_modifying_user.display_name,
        original_content: content,
        version: file.version
      }
      cg.save
      cg
    end

    def sort_by_grade
      includes(taggings: :tag).sort_by(&:grade_score)
    end
  end

  def grades
    @grades ||= Grades.new(self)
  end

  def faq
    ContentGuideFaq.where_subject(subject).try(:first)
  end

  def grade_score
    indices =
      taggings.map do |t|
        grade = t.tag.name if t.context == 'grades'
        Grades::GRADES.index(grade)
      end.compact

    [indices.min || 0, indices.size]
  end

  def modified_by
    "#{last_modifying_user_name} <#{last_modifying_user_email}>" if last_modifying_user_name.present?
  end

  def non_existent_podcasts
    @non_existent_podcasts ||= begin
      presenter.podcast_links.map { |a| a[:href] }.reject do |url|
        Resource.find_podcast_by_url(url)
      end
    end
  end

  def non_existent_videos
    @video_links ||= presenter.video_links
    @non_existent_videos ||= begin
      @video_links.map { |a| a[:href] }.reject do |url|
        Resource.find_video_by_url(url)
      end
    end
  end

  def broken_internal_links
    @video_links ||= presenter.video_links
    @broken_links ||= begin
      presenter.internal_links_refs - @video_links.map { |a| a[:id] }.compact.uniq
    end
  end

  def original_url
    "https://docs.google.com/document/d/#{file_id}/edit"
  end

  def paragraphs_with_invalid_icons
    @paragraphs_with_invalid_icons ||= begin
      presenter.icons.map do |icon|
        icon.parent unless ICON_VALUES.include?(icon['data-value'])
      end.compact
    end
  end

  # "Fuzzy" CG identificator
  def permalink_or_id
    if permalink.present?
      permalink
    else
      id
    end
  end

  def validate_metadata
    @validate_metadata = true
    valid?
  end

  private

  def assign_common_core_standards(value)
    names = split_list(value)
    name_node = Standard.where(name: names).where_values.reduce(:and)
    alt_names_node = Standard.where.overlap(alt_names: names).where_values.reduce(:and)
    self.common_core_standards = CommonCoreStandard.where(name_node.or(alt_names_node))
  end

  def assign_grades(value)
    grades = split_list(value)
    grades.map! do |grade|
      case grade
      when 'k' then 'kindergarten'
      when 'pk' then 'prekindergarten'
      else "grade #{grade}"
      end
    end
    self.grade_list = grades
  end

  def assign_subject(value)
    subject = value.strip.downcase
    self.subject = subject if %w(ela math).include?(subject)
  end

  def assign_unbounded_standards(value)
    names = split_list(value)

    unbounded_standards.where.not(name: names).each do |standard|
      content_guide_standards.find_by_standard_id(standard.id).delete
    end

    names.each do |name|
      standard = UnboundedStandard.create_with(subject: '').find_or_create_by(name: name)
      unbounded_standards << standard if standard && !unbounded_standards.include?(standard)
    end
  end

  def downcase(str)
    str.mb_chars.downcase.to_s rescue nil
  end

  def downcase_permalink
    self.permalink = downcase(permalink)
    true
  end

  def download_images(doc)
    doc.css('img').each do |img|
      url = img[:src]
      if (image = ContentGuideImage.find_or_create_by_original_url(url))
        img[:src] = image.file.url
      end
    end
    doc
  end

  def extract_links(doc)
    doc.css('a[href^="https://www.google.com/url"]').each do |a|
      url = URI(a[:href])
      params = Rack::Utils.parse_query(url.query)
      a[:href] = params['q']
      a[:target] = '_blank'
    end
    doc
  end

  def set_slug
    value = update_metadata ? slug : title
    return true unless value.present?

    value = downcase(value)
    self.slug = value.gsub(/(_|[[:space:]])/, '-').gsub(/[^-[[:alnum:]]]/, '').gsub(/-+/, '-')
  end

  def icon_values
    errors.add(:base, 'paragraphs with invalid icons') if paragraphs_with_invalid_icons.any?
  end

  def media_exist
    errors.add(:base, 'media does not exist') if non_existent_podcasts.any? || non_existent_videos.any?
  end

  def no_broken_ext_links
    errors.add(:base, 'broken ext links') if broken_ext_links.any?
  end

  def no_broken_internal_links
    errors.add(:base, 'broken internal links') if broken_internal_links.any?
  end

  def presenter
    @presenter ||= ContentGuidePresenter.new(self)
  end

  def process_content
    doc = Nokogiri::HTML(original_content)
    doc = HtmlSanitizer.process_list_styles(doc)
    body = doc.xpath('/html/body/*').to_s
    body = Nokogiri::HTML.fragment(body)
    body = download_images(body)
    body = extract_links(body)
    body = process_metadata(body)
    self.content = body.to_s
  end

  def process_metadata(doc)
    table = doc.at_css('table')
    return doc unless table

    table.search('br').each { |br| br.replace("\n") }
    table.css('tr').each do |tr|
      key, value = tr.css('td').map(&:content).map(&:strip)
      case key
      when 'ccss' then assign_common_core_standards(value)
      when 'related_instruction_tags' then assign_unbounded_standards(value)
      when 'big_photo', 'small_photo' then send("remote_#{key}_url=", value)
      when 'grade', 'grades' then assign_grades(value)
      when 'subject' then assign_subject(value)
      else send("#{key}=", value) # TODO: what if key is blank?
      end
    end

    table.remove
    doc
  end

  def split_list(value)
    value.split(',').map(&:strip).map(&:downcase)
  end

  def tasks_have_break
    errors.add(:base, :invalid) if tasks_without_break.any?
  end

  def validate_metadata?
    !!@validate_metadata
  end
end

app/controllers/admin/content_guides_controller.rb
module Admin
  class ContentGuidesController < AdminController
    include GoogleAuth

    before_action :obtain_google_credentials, only: :import
    before_action :load_content_guide, only: %i(edit update)

    def index
      @content_guides = ContentGuide.sort_by_grade
    end

    def reset_pdfs
      ContentGuide.find_each do |cg|
        cg.remove_pdf!
        cg.save!
      end
      redirect_to({ action: :index }, notice: 'Cached PDFs were reset')
    rescue Excon::Errors::Error => e
      redirect_to({ action: :index }, alert: e.to_s)
    end

    def edit
      @content_guide.validate_metadata
    end

    def update
      if @content_guide.update(content_guide_params)
        redirect_to :admin_content_guides, notice: t('.success', name: @content_guide.name)
      else
        render :edit
      end
    end

    def destroy
      content_guide = ContentGuide.find(params[:id])
      content_guide.destroy
      redirect_to :admin_content_guides, notice: t('.success', name: content_guide.name)
    end

    # GET /content_guides/import
    def import
      file_id = ContentGuide.file_id_from_url(params[:content_guide][:url])
      redirect_to(:new_admin_content_guide, alert: 'Incorrect link!') and return if file_id.blank?

      @content_guide = ContentGuide.import(file_id, google_credentials)
      return unless @content_guide.errors.empty?
      redirect_to [:edit, :admin, @content_guide], notice: t('.success', name: @content_guide.name)
    end

    # GET /content_guides/links_validation
    def links_validation
      @content_guides = ContentGuide.all.map { |d| ContentGuidePresenter.new(d, request.base_url, view_context) }
    end

    private

    def load_content_guide
      @content_guide = ContentGuide.find(params[:id])
    end

    def content_guide_params
      params
        .require(:content_guide)
        .permit(:date, :description, :slug, :subject, :teaser, :title, :update_metadata,
                common_core_standard_ids: [], grade_list: [], unbounded_standard_ids: [])
    end
  end
end

app/controllers/content_guides_controller.rb
class ContentGuidesController < ApplicationController
  include AnalyticsTracking

  before_action :find_content_guide

  def show; end

  def show_pdf
    return render(interactor.pdf_params) if interactor.debug?

    cg = interactor.content_guide
    ga_track_download(action: content_guide_path(cg.permalink_or_id, cg.slug), label: '')

    # TODO Refactor and make it actually work
    # cg.pdf_refresh!(url_for(nocache: ''))
    redirect_to cg.pdf_url
  end

  protected

  def find_content_guide
    @content_guide = interactor.presenter
  end

  def interactor
    ContentGuidesInteractor.call(self)
  end
end

app/helpers/admin/content_guides_helper.rb
# frozen_string_literal: true

module Admin
  module ContentGuidesHelper
    def content_guide_nav(cg)
      Rails.cache.fetch("content_guides:#{cg.id}:nav") { render partial: 'nav', locals: { cg: cg } }
    end
  end
end

app/views/admin/content_guides/_broken_links_list.html.erb
<% if urls.any? %>
  <li class='accordion-item is-active' data-accordion-item>
    <%= link_to '#', class: 'accordion-title' do %>
      <h3><%= title %></h3>
    <% end %>

    <div class=accordion-content data-tab-content>
      <ol>
        <% urls.each do |url| %>
          <li><%= link_to url, url %>
        <% end %>
      </ol>
    </div>
<% end %>

app/views/admin/content_guides/_photo.html.erb
<% if url = @content_guide.send(attr).url %>
  <div class=input>
    <label><%= ContentGuide.human_attribute_name(attr) %></label>
    <%= image_tag url, style: 'margin-bottom: 1rem' %>
  </div>
<% end %>

app/views/admin/content_guides/dangling_links.html.erb
<div class=o-page>
  <h2 class=text-center><%= t('.page_title') %></h2>

  <% @content_guides.each do |content_guide| %>
    <% if (dangling_links = content_guide.dangling_links).any? %>
      <h4>
        <%= link_to content_guide.name, content_guide %>
        /
        <%= link_to ContentGuide.human_attribute_name(:original_url), content_guide.original_url %>
      </h4>
      <ol>
        <% dangling_links.each do |dangling_link| %>
          <li><%= link_to dangling_link.text, dangling_link.url %>
        <% end %>
      </ol>
    <% end %>
  <% end %>
</div>

app/views/admin/content_guides/edit.html.erb
<div class=o-page>
  <h2 class=text-center><%= t('.page_title') %></h2>

  <%= simple_form_for [:admin, @content_guide] do |f| %>
    <%= f.input :update_metadata, as: :hidden %>
    <%= f.input :title, as: :text, input_html: { rows: 2 } %>
    <%= f.input :teaser %>
    <%= f.input :permalink, input_html: { disabled: true } %>
    <%= f.input :slug %>
    <%= f.input :subject, as: :select, collection: t(:subjects).map { |k, v| [v, k] } %>
    <%= f.input :grade_list, collection: Tag.select(:id, :name).distinct(:name).where_context('grades'), as: :select, value_method: :name, selected: @content_guide.grades, input_html: { class: 'selectize', multiple: true } %>
    <%= f.input :date %>
    <%= f.input :description, as: :text %>
    <%= f.association :common_core_standards, as: :select, input_html: { class: 'selectize', multiple: true } %>
    <%= f.association :unbounded_standards, as: :select, input_html: { class: 'selectize', multiple: true } %>

    <%= render partial: 'photo', locals: { attr: :big_photo }%>

    <%= render partial: 'photo', locals: { attr: :small_photo }%>

    <%= f.button :submit, t('ui.save') %>
    <%= link_to t('ui.delete'), [:admin, @content_guide], class: 'button alert', data: { confirm: t('ui.are_you_sure') }, method: :delete %>
  <% end %>
</div>

app/views/admin/content_guides/import.html.erb
<% page_title = t('.page_title', name: @content_guide.name) %>

<% set_page_title page_title %>

<div class="o-page">
  <h2 class=text-center><%= page_title %></h2>

  <div>
    <ui class=accordion data-accordion>
      <% if (errors = @content_guide.errors.full_messages.select { |m| m != 'is invalid' }).any? %>
        <li class='accordion-item is-active' data-accordion-item>
          <%= link_to '#', class: 'accordion-title' do %>
            <h3><%= t('.common_errors') %></h3>
          <% end %>

          <div class=accordion-content data-tab-content>
            <ol>
              <% errors.each do |error| %>
                <li><%= error %>
              <% end %>
            </ol>
          </div>
      <% end %>

      <% if (pars = @content_guide.paragraphs_with_invalid_icons).any? %>
        <li class='accordion-item is-active' data-accordion-item>
          <%= link_to '#', class: 'accordion-title' do %>
            <h3><%= t('.invalid_icons') %></h3>
          <% end %>

          <div class=accordion-content data-tab-content>
            <ol>
              <% pars.each do |par| %>
                <li><%= par.to_s.html_safe %>
              <% end %>
            </ol>
          </div>
      <% end %>

      <%= render 'broken_links_list', title: t('.broken_ext_links_error'), urls: @content_guide.broken_ext_links %>

      <%= render 'broken_links_list', title: t('.broken_int_links_error'), urls: @content_guide.broken_internal_links %>

      <%= render 'broken_links_list', title: t('.non_existent_videos_error'), urls: @content_guide.non_existent_videos %>

      <%= render 'broken_links_list', title: t('.non_existent_podcasts_error'), urls: @content_guide.non_existent_podcasts %>
    </ul>
  </div>
</div>

app/views/admin/content_guides/index.html.erb
<div class="o-page">
  <h2 class=text-center><%= t('.page_title') %></h2>
  <%= link_to 'Reset PDFs', reset_pdfs_admin_content_guides_path,
    class: %w[button pull-right], data: { confirm: 'Are you sure?' }, method: :post %>

  <table class=table>
    <tr>
      <th><%= ContentGuide.human_attribute_name :name %>
      <th><%= ContentGuide.human_attribute_name :title %>
      <th><%= ContentGuide.human_attribute_name :subject %>
      <th><%= ContentGuide.human_attribute_name :grade_list %>
      <th><%= ContentGuide.human_attribute_name :modified_by %>
      <th><%= ContentGuide.human_attribute_name :version %>
      <th>
    </tr>

    <% @content_guides.each do |content_guide| %>
      <tr>
        <td><%= link_to content_guide.title, content_guide_path(content_guide.permalink_or_id, content_guide.slug) %>
        <td><%= content_guide.title %>
        <td><%= t(content_guide.subject, scope: :subjects) if content_guide.subject %>
        <td>
          <% content_guide.grades.list.each do |grade| %>
            <span class=text-nowrap><%= grade %></span>
            <br>
          <% end %>
        <td><%= content_guide.modified_by %>
        <td><%= content_guide.version %>
        <td class=text-nowrap>
          <%= link_to t('ui.edit'), [:edit, :admin, content_guide], class: 'button' %>
          <%= link_to t('.original_document'), content_guide.original_url, class: 'button', target: '_blank' %>
          <%= link_to t('ui.reimport'), import_admin_content_guides_path(content_guide: { url: content_guide.original_url }), class: 'button', 'data-no-turbolink' => true %>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/content_guides/links_validation.html.erb
<div class=o-page>
  <h2 class=text-center><%= t('.page_title') %></h2>

  <% @content_guides.each do |content_guide| %>
    <% if (dangling_links = content_guide.dangling_links).any? %>
      <h4>
        <%= link_to content_guide.name, content_guide %>
        /
        <%= link_to ContentGuide.human_attribute_name(:original_url), content_guide.original_url %>
      </h4>
      <ol>
        <% dangling_links.each do |dangling_link| %>
          <li><%= link_to dangling_link.text, dangling_link.url %>
        <% end %>
      </ol>
    <% end %>
  <% end %>
</div>

app/views/admin/content_guides/new.html.erb
<div class="o-page">
  <h2 class=text-center><%= t('.page_title') %></h2>
  
  <%= simple_form_for :content_guide, url: [:import, :admin, :content_guides], html: { method: :get } do |f| %>
    <%= f.input :url, label: t('ui.url') %>
    <%= f.button :submit, t('.submit') %>
  <% end %>
</div>