config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/' => 'welcome#index'

  get '/404'          => 'pages#not_found'
  # get '/about'        => 'pages#show_slug', slug: 'about'
  # get '/about/people' => 'pages#show_slug', slug: 'about_people'
  get '/tos'          => 'pages#show_slug', slug: 'tos',     as: :tos_page
  get '/privacy'      => 'pages#show_slug', slug: 'privacy', as: :privacy_page
  # get '/leadership'   => 'pages#leadership'
  get '/forthcoming'  => 'pages#forthcoming'

  get '/search' => 'search#index'

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  resources :downloads, only: [:show] do
    member do
      get :preview
    end
  end
  get '/downloads/:id/pdf_proxy(/:s3)',
      as: :pdf_proxy_download, to: 'downloads#pdf_proxy', constraints: { s3: %r{[^\/]+} }
  get '/downloads/content_guides/:id(/:slug)', as: :content_guide_pdf, to: 'content_guides#show_pdf'
  resources :explore_curriculum, only: %i(index show)
  resources :enhance_instruction, only: :index
  resources :find_lessons, only: :index
  resources :pages, only: :show
  resources :resources, only: :show do
    get :pdf_proxy, on: :collection, path: 'pdf-proxy'
  end
  resource :survey, only: %i(create show)

  get '/resources/:id/related_instruction' => 'resources#related_instruction', as: :related_instruction
  get '/media/:id' => 'resources#media', as: :media
  get '/other/:id' => 'resources#generic', as: :generic
  get '/content_guides/:id(/:slug)', as: :content_guide, to: 'content_guides#show'

  resources :documents, only: :show do
    member do
      post 'export', to: 'documents#export'
      get 'export/status', to: 'documents#export_status'
      post 'lti', to: 'documents#show_lti'
    end
  end
  resources :materials, only: :show do
    member do
      get 'preview/pdf', to: 'materials#preview_pdf'
      get 'preview/gdoc', to: 'materials#preview_gdoc'
    end
  end

  devise_for :users, class_name: 'User', controllers: { registrations: 'registrations', sessions: 'sessions' }

  authenticate :user do
    mount Resque::Server, at: '/queue'
  end

  namespace :admin do
    get '/' => 'welcome#index'
    get 'google_oauth2_callback' => 'google_oauth2#callback'
    get '/association_picker' => 'association_picker#index'
    resources :content_guide_definitions, only: %i(index new) do
      get :import, on: :collection
    end
    resources :content_guides, except: :create do
      collection do
        get :import
        get :links_validation
        post :reset_pdfs
      end
    end
    resources :reading_assignment_texts
    resource :resource_bulk_edits, only: %i(new create)
    get '/resource_picker' => 'resource_picker#index'
    resources :resources, except: :show do
      member do
        post :export_to_lti_cc, path: 'export-lti-cc'
        post :unit_bundle
      end
    end
    resources :download_categories, except: :show
    resources :pages, except: :show
    resources :settings, only: [] do
      patch :toggle_editing_enabled, on: :collection
    end
    resources :staff_members, except: :show
    resources :users, except: :show do
      post :reset_password, on: :member
    end
    resources :leadership_posts, except: :show
    resources :content_guide_faqs, except: :show
    resources :standards, only: %i(index edit update)

    resources :components, only: %i(index show)
    resource :sketch_compiler, path: 'sketch-compiler', only: [] do
      get '/', to: 'sketch_compilers#new', defaults: { version: 'v1' }
      get '/:version/new', to: 'sketch_compilers#new', as: :new
      post '/:version/compile', to: 'sketch_compilers#compile', as: :compile
    end
    resources :documents, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'documents#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'documents#import_status'
      end
    end
    resources :materials, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'materials#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'materials#import_status'
      end
    end
    resources :documents, only: %i(index create new destroy)
    resources :materials, only: %i(index create new destroy)
    resource :curriculum, only: %i(edit update)
    resources :access_codes
    resource :batch_reimport, only: %i(new create)
  end

  get '/*slug' => 'resources#show', as: :show_with_slug
end

app/views/resources/_bilingual_standards.html.erb
<% if (resource.unit? || resource.lesson?) && standards.present? %>
<div class="o-resource__item">
  <h3>Bilingual Language Progressions</h3>
  <p>These resources, developed by the New York State Education Department, provide standard-level scaffolding suggestions for English Language Learners (ELLs) to help them meet grade-level demands. Each resource contains scaffolds at multiple levels of language acquisition and describes the linguistic demands of the standards to help ELA teachers as well as ESL/bilingual teachers scaffold content for their English learning students.</p>
  <div class="o-bilingual-stds o-resource__list--<%= color_code %>">
  <% standards.each do |standard| %>
    <div class="o-bilingual-stds__item">
      <%= link_to t('resources.bilingual.standard_title', std: standard.short_name),
                  download_path(standard, slug: resource.slug, type: 'standard')%>
    </div>
  <% end %>
</div>
</div>
<% end %>

app/views/resources/_children_list.html.erb
<% unless resource.lesson? %>
  <h3><%= t('resources.title.children', type: type_name(resource)) %></h3>
  <%= 'No children items.' if resource.children.blank? %>
  <ul class="o-resource__list o-resource__list--icons o-resource__list--<%= color_code %>">
    <% resource.children.each do |item| %>
      <li>
        <i class="fa fa-square"></i>
        <span>
          <% title = "#{item.short_title}: " %>
          <% if item.document.present? %>
            <%= link_to document_path(item.document) do %>
              <span class="u-text--capitalized"><%= title %></span>
              <%= item.title %>
            <% end%>
          <% else %>
            <%= link_to show_with_slug_path(item.slug) do %>
              <span class="u-text--capitalized"><%= title %></span>
              <%= item.title %>
            <% end%>
          <% end%>
        </span>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/resources/_copyright_icons_generic.html.erb
<% cc_types = [{ icon: 'cc-zero', title: 'You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.' }] %>

<% if resource.copyrights.present? %>
  <% cc_types.each do |cc_type| %>
    <span data-tooltip data-template-classes="u-resource-tooltip cs-tint-bg--<%= color_code(resource, base: true) %>" aria-haspopup="true" title="<%= cc_type[:title] %>">
        <i class="fa-lg ub-<%= cc_type[:icon] %>"></i>
    </span>
  <% end %>
<% end %>

app/views/resources/_download.html.erb
<li>
  <% if download.download.attachment_content_type == 'pdf' %>
    <span>
      <%= link_to preview_download_path(id: download, slug: resource.slug), class: 'resource-attachment',
        data: { no_turbolink: true, heap_data: download_heap_data(download, pdf_preview: true) }, target: '_blank' do %>
        <i class="ub-icon ub-eye" aria-hidden="true"></i>
      <% end %>
    </span>
  <% end %>
  <% id = SecureRandom.hex(4) %>
  <span data-toggle="<%= id %>">
    <%= link_to download_path(download, slug: resource.slug), class: 'resource-attachment', data: { no_turbolink: true, heap_data: download_heap_data(download) } do %>
      <i class="ub-icon fa-lg file-<%= "#{file_icon(download.download.attachment_content_type)} #{indent}" %>"></i>
      <%= download.download.title %>
    <% end %>
  </span>
  <% if (description = download.description).present? %>
    <span class="dropdown-pane o-ld-dropdown"
          data-dropdown
          data-hover="true"
          data-hover-delay="0"
          data-hover-pane="true"
          data-v-offset="12"
          id="<%= id %>">
      <%= description %>
    </span>
  <% end %>
</li>

app/views/resources/_download_form.html.erb
<div class="o-download-modal" id="downloads-modal" data-reveal> <!-- modal content -->
  <div class="o-download-modal__title">
    <div class="u-margin-bottom--xs">Download <%= resource.resource_type.humanize %></div>
    <div class="u-hr-small"></div>
  </div>
  <div class="o-download-modal__content">
    <ul class="o-resource__list o-resource__list--icons o-resource__list--<%= resource.subject %>-base">
      <% resource.download_categories.each do |k, downloads| %>
        <strong><%= k %></strong>
        <% indent = resource.downloads_indent category: downloads.first&.download_category %>
        <% downloads.select { |d| d.is_a?(ResourceDownload) }.each do |download| %>
          <%= render partial: 'resources/download', locals: { download: download, resource: @resource, indent: indent } %>
        <% end %>
      <% end %>
    </ul>
    <div class="o-resource__cc u-margin-top--base u-margin-bottom--zero u-txt--download-copyright">
      <%= render partial: 'resources/copyright_icons_generic', locals: { resource: resource } if resource.generic? %>
      <%= copyrights_text(resource) %>
    </div>
  </div>
  <button class="close-button ub-close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true"><i class="ub-close"></i></span>
  </button>
</div>

app/views/resources/_downloads.html.erb
<div id="resource-downloads-list" class="o-resource__item">
  <h3>Downloads</h3>
  <% if resource.download_categories.any? %>
    <% resource.download_categories.each_with_index do |(category_title, downloads), idx| %>
      <%# Hard positioning bundles on the 2nd %>
      <%= render partial: 'resources/unit_bundles', locals: { resource: resource } if idx == 1 %>

      <h4 class="<%= 'u-margin-top--xs' if category_title.present? %>"><%= category_title %></h4>
        <% if (resource_download = downloads.first) %>
          <% category = resource_download.download_category %>
          <% settings = resource.download_categories_settings[category_title.parameterize] %>
          <% if settings.try(:[], 'show_short_description') %>
            <p><%= resource_download.try(:short).presence || category&.description %></p>
          <% end %>
          <% if settings.try(:[], 'show_long_description') %>
            <div><%= raw resource_download.try(:long).presence || category&.long_description %></div>
          <% end %>
          <%  %>
          <% indent = resource.downloads_indent category: category %>
          <% if (downloads_ext = downloads.take(download_per_category_limit)).any? %>
            <ul class="o-resource__list o-resource__list--icons o-resource__list--<%= color_code(resource, base: true) %>">
              <% downloads_ext.each do |download| %>
                <%= render(partial: 'resources/download', locals: { download: download, resource: resource, indent: indent }) if download.is_a?(ResourceDownload) %>
              <% end %>
            </ul>
          <% end %>
          <% if downloads.size > download_per_category_limit %>
            <div class="o-resource-downloads">
              <div class="o-resource-downloads__btn o-resource-downloads__btn--more"><%= t('ui.show_more') %></div>
              <div class="o-resource-downloads__list">
                <ul class="o-resource__list o-resource__list--icons o-resource__list--<%= color_code(resource, base: true) %>">
                  <% downloads[download_per_category_limit..-1].each do |download| %>
                    <%= render(partial: 'resources/download', locals: { download: download, resource: resource, indent: indent }) if download.is_a?(ResourceDownload) %>
                  <% end %>
                </ul>
              </div>
              <div class="o-resource-downloads__btn o-resource-downloads__btn--less"><%= t('ui.show_less') %></div>
            </div>
          <% end %>
        <% end %>
    <% end %>
  <% elsif resource.unit_bundles? %>
    <%= render partial: 'resources/unit_bundles', locals: { resource: resource } %>
  <% elsif resource.downloads.empty? %>
    <span>There are no downloads for this resource</span>
  <% end %>
</div>

app/views/resources/_engageny.html.erb
<% cc_types = [{ icon: 'cc-stamp', title: 'Creative Commons' },
               { icon: 'cc-by', title: 'Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.' },
               { icon: 'cc-nc', title: 'NonCommercial — You may not use the material for commercial purposes.' },
               { icon: 'cc-sa', title: 'ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.' },
              ]
%>

<% if resource.engageny_url %>
  <!-- "cc-nd", "cc-pd", "cc-zero", "cc-share", "cc-remix" -->
  <ul class="menu horizontal">
    <% cc_types.each do |cc_type| %>
      <li>
        <span data-tooltip data-template-classes="u-resource-tooltip cs-tint-bg--<%= color_code %>" aria-haspopup="true" title="<%= cc_type[:title] %>">
          <i class="fa-lg ub-<%= cc_type[:icon] %>"></i>
        </span>
      </li>
    <% end %>
  </ul>
  <!--div class="o-resource__cc">From EngageNY.org of the New York State Education Department. <%= resource.engageny_title.strip %>.
    <%# if url = resource.engageny_url %>
      Available from <%#= url.gsub(/^(https?:\/\/)?(www\.)?/, '') %>; accessed 2015-05-29.
    <%# end %>
  </div-->
<% end %>

<div class=o-resource__cc>
  <%= copyrights_text(resource) %>
</div>

app/views/resources/_header.html.erb
<div class="o-page__section cs-bg--<%= color_code(resource) %> u-br-top-right--base">
  <div class="o-content-title u-text--capitalized">
    <%= resource_breadcrumbs_with_links(resource) %>
  </div>
</div>

app/views/resources/_prerequisites_standards.html.erb
<% standards = prerequisites_standards(resource) %>
<% if standards.present? %>
<div class="o-resource__item">
  <h3>Prerequisites</h3>
  <ul class="o-resource__taglist o-resource__list--<%= color_code(resource, base: true) %>">
  <% standards.each_with_index do |standard, i| %>
    <li>
      <%= link_to standard, search_path(search_term: standard) %><%= ', ' if i != standards.size - 1  %>
    </li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/resources/_tags.html.erb
<div class="o-resource__item">
  <h3>Tags</h3>
  <% each_tags_cloud!(tag_clouds) do |tags, cloud_name = nil| %>
    <ul class="o-resource__taglist o-resource__list--<%= color_code %>">
      <% if cloud_name.present? %>
        <li><strong><%= cloud_name %>:</strong></li>
      <% end %>
      <% tags.each_with_index do |tag, i| %>
        <li>
          <%= link_to tag, search_path(search_term: tag.downcase) %><%= ', ' if i != tags.size - 1  %>
        </li>
      <% end %>
      <% if tags.empty? %>
        <span>There are no tags for this resource</span>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/resources/_unit_bundles.html.erb
<div class="o-unit-bundles">
  <h4>Lessons Materials</h4>
  <p>Download teacher and student materials for all lessons in PDF or Google Docs format.</p>
  <% DocumentBundle::CATEGORIES.each do |cat| %>
    <% if (bundle = resource.document_bundles.detect { |b| b.content_type == 'pdf' && b.category == cat }) %>
      <ul class="o-resource__list o-resource__list--icons o-resource__list--<%= color_code(resource, base: true) %>">
        <li class="o-unit-bundles__item">
          <div class="o-unit-bundles__item--links">
            <%= link_to bundle.file&.url, data: { no_turbolink: true, heap_data: bundle_heap_data(resource, bundle, cat, 'pdf') } do %>
              <i class="ub-icon fa-lg ub-file-zip"></i>
            <% end %>
            <% if (gdoc_bundle =  resource.document_bundles.detect { |b| b.content_type == 'gdoc' }) %>
              <% if cat == 'full' %>
                <%= link_to gdoc_bundle.url, target: '_blank', data: { no_turbolink: true, heap_data: bundle_heap_data(resource, gdoc_bundle, :full, 'gdoc') } do %>
                  <i class="ub-icon fa-lg ub-file-gdoc"></i>
                <% end %>
              <% else %>
                <span class="o-unit-bundles__item--placeholder"></span>
              <% end %>
            <% end %>
            <span><%= t("bundles.#{cat}") %></span>
          </div>
        </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/resources/generic.html.erb
<% set_page_title @resource.title %>
<% set_social_media_sharing @resource %>

<div class="o-page o-page--margin-to-bottom">
  <div class="o-page__module u-margin-bottom--gutter">
    <%= link_to enhance_instruction_index_path(tab: 2), class: 'o-ub-btn o-ub-btn--base o-btn--xs-full' do %>
      <i class="fa-lg ub-arrow-left u-text--middled"></i> <%= t('instructions.btn.back') %>
    <% end %>
  </div>
  <%= render partial: 'resources/header', locals: { resource: @resource } %>
  <div class="o-page__section u-padding-top--gutter u-bg--light">
    <div class="o-resource-title">
      <div class="o-resource-title__title">
        <div class="o-title u-text--uppercase">
          <span class="o-title__type cs-txt--<%= color_code(@resource) %>"><%= @resource.type_name %></span>
          <!-- <span class="o-title__duration"><%= react_component('TimeToTeach', {duration: @resource.time_to_teach}, prerender: true) %></span> -->
        </div>
        <h1><%= @resource.title %></h1>
        <div class="u-txt--teaser o-social-sharing__teaser">
          <%= @resource.teaser %>
        </div>
      </div>
      <div class="o-resource-title__links">
        <div>
          <a class="o-ub-btn o-ub-btn--yellow <%= 'o-ub-btn--disabled' if @resource.downloads.empty? %>" data-open="downloads-modal">
            <%= t('resources.btn.download', title: @resource.type_name) %>
          </a>
        </div>
      </div>
    </div>
    <hr class="o-resource-hr">
    <div class="o-resource-summary u-padding-bottom--gutter">
      <div class="o-resource-summary__map">
        <%= render partial: 'shared/social_sharing', locals: { resource: @resource, cl: '' } %>
      </div>
      <div class="o-resource-summary__content">
        <% if @resource.preview? %>
          <div class="o-generic-preview">
            <canvas id="o-generic-preview__canvas" class="o-generic-preview__canvas"></canvas>
            <button class="o-generic-preview__btn o-ub-btn--show-more o-ub-btn--force-disabled">
              <%= t('ui.show_more') %>
            </button>
          </div>
        <% end %>
        <div class="o-resource__item o-resource__item--description">
          <h3>Description</h3>
          <%= @resource.description.try(:html_safe) %>
        </div>
        <%= render partial: 'resources/downloads', locals: { resource: @resource } %>
        <%= render partial: 'resources/prerequisites_standards', locals: { resource: @resource } %>
        <%= render_tag_clouds(@resource) %>
        <% if @resource.copyright_attributions.present? %>
        <div class="o-resource__item o-resource__item--credits">
          <h3>Credits</h3>
          <%= render partial: 'resources/engageny_generic', locals: { resource: @resource, color_code: color_code(@resource) } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render partial: 'resources/download_form', locals: { resource: @resource } %>
</div>

<% if @resource.preview? %>
  <script type="text/javascript" data-turbolinks-eval="always">
    pdfUrl="<%= pdf_proxy_download_path(@resource.pdf_preview_download, s3: @resource.pdf_preview_download.download.s3_filename) %>"
  </script>
<% end %>

app/views/resources/media.html.erb
<% set_page_title @resource.title %>
<% set_social_media_sharing @resource %>

<div class="o-page o-page--margin-to-bottom">
  <div class="o-page__module u-margin-bottom--gutter">
    <%= link_to enhance_instruction_index_path(tab: 1), class: 'o-ub-btn o-ub-btn--base o-btn--xs-full' do %>
      <i class="fa-lg ub-arrow-left u-text--middled"></i> <%= t('instructions.btn.back') %>
    <% end %>
  </div>
  <div class="o-page__section cs-bg--<%= color_code(@resource) %>">
    <div class="o-content-title u-text--capitalized">
      <%= @resource.media_title %>
    </div>
  </div>
  <div class="o-page__section u-padding-top--gutter u-bg--light">
    <div class="o-resource-title">
      <div class="o-resource-title__title">
        <!--div class="o-title u-text--uppercase">
          <span class="o-title__duration"><%= react_component('TimeToTeach', {duration: @resource.time_to_teach}, prerender: true) %></span>
        </div-->
        <h1><%= @resource.title %></h1>
        <div class="u-txt--teaser o-social-sharing__teaser">
          <%= @resource.teaser %>
        </div>
      </div>
    </div>
    <hr class="o-resource-hr">
    <div class="o-resource-summary u-padding-bottom--gutter">
      <div class="o-resource-summary__map">
        <%= render partial: 'shared/social_sharing', locals: { resource: @resource, cl: '' } %>
      </div>
      <div class="o-resource-summary__content">
        <div class="o-resource__item o-resource-summary__content--media">
          <div class="o-media-<%= @resource.resource_type %>">
            <%= embed_media(@resource) %>
          </div>
        </div>
        <div class="o-resource__item o-resource__item--description">
          <h3>Description</h3>
          <%= @resource.description.try(:html_safe) %>
        </div>
        <%= render_tag_clouds(@resource) %>
        <% if @resource.engageny_url %>
        <div class="o-resource__item o-resource__item--credits">
          <h3>Credits</h3>
          <%= render partial: 'resources/engageny', locals: { resource: @resource, color_code: color_code(@resource) } %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="o-resource-summary--2x u-pd-content--xlarge cs-tint-bg--<%= color_code(@resource) %>">
      <div class="o-resource-summary__map o-resource-summary__map--2x"></div>
      <div class="o-resource-summary__content--2x">
        <h3><%= t('.related_guides_title') %></h3>
        <p><%= t('.related_guides_subtitle', type: @resource.resource_type) %>
      </div>
    </div>
  </div>
</div>

app/views/resources/show.html.erb
<% set_page_title @resource.page_title %>
<% set_social_media_sharing @resource %>

<% set_canonical_url(show_with_slug_path @resource.slug) if @resource.slug %>

<div class="o-page o-page--margin-to-bottom o-page--resource">
  <div class="o-page__sticky">
    <div class="o-sticky o-sticky--left <%= 'o-sticky--disabled' unless @resource.previous %>">
      <a class="o-sticky__btn o-sticky--left__btn" href="<%= @resource.previous ? show_with_slug_path(@resource.previous.slug) : '#' %>">
        <div class="o-page__wrap--row o-sticky__wrap o-sticky__wrap--left">
          <div class="o-sticky__icon <%= 'u-link--disabled' unless @resource.previous %>">
            <i class="fa-3x ub-angle-left"></i>
          </div>
          <% if @resource.previous %>
            <div class="o-sticky__txt hide-for-small-only">
              <div class="o-sticky__arrow-subheader"><%= t('resources.btn.arrow', dir: 'Previous', type: type_name(@resource.previous)) %></div>
              <div class="o-sticky__arrow-header"><%= @resource.previous.title %></div>
            </div>
          <% end %>
          <div class="o-sticky__txt show-for-small-only <%= 'u-link--disabled' unless @resource.previous %>">
            <div class="o-sticky__arrow-subheader"><%= t('resources.btn.arrow-small', dir: 'Previous', type:  type_name(@resource)) %></div>
            <div class="o-sticky__arrow-header"><%= t('resources.btn.arrow-txt-small') %></div>
          </div>
        </div>
      </a>
    </div>
  </div>
  <div class="o-page__module">
    <div class="o-page__wrap--row">
      <div class="o-page__module u-margin-bottom--gutter">
        <%= link_to back_to_resource_path(@resource), class: 'o-btn o-btn--base o-btn--xs-full' do %>
          <i class="fa-lg ub-arrow-left u-text--middled"></i> <%= t('resources.btn.back') %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to edit_admin_resource_path(@resource), class: 'o-btn o-btn--base', target: '_blank' do %>
            <%= t('ui.edit') %>
          <% end %>
        <% end %>
      </div>
      <%= render partial: 'resources/header', locals: { resource: @resource } %>
      <div class="o-page__section u-padding-top--gutter u-bg--light u-br-top-right--base u-br-bottom--base">
        <div class="o-resource-title">
          <div class="o-resource-title__title">
            <div class="o-title u-text--uppercase">
              <span class="o-title__type cs-txt--<%= color_code(@resource) %>"><%= @resource.short_title %></span>
              <span class="o-title__duration u-hidden"><%= react_component('TimeToTeach', {duration: @resource.time_to_teach}, prerender: true) %></span>
            </div>
            <h1><%= @resource.title %></h1>
            <div class="u-txt--teaser o-social-sharing__teaser">
              <%= @resource.teaser %>
            </div>
          </div>
          <div class="o-resource-title__links">
            <div>
              <%= link_to t('resources.btn.related'), '#related-instruction', class: 'o-ub-btn o-ub-btn--2bordered-gray' %>
            </div>
          </div>
        </div>
        <hr class="o-resource-hr">
        <div class="o-resource-summary u-padding-bottom--gutter">
          <div class="o-resource-summary__map">
            <div class="o-resource-summary__title">
              <strong><%= @resource.subject_and_grade_title %> Curriculum Map</strong>
            </div>
            <%= react_component('CurriculumMap', @props.merge(mapType: 'cs'), prerender: true) %>
            <%= render partial: 'shared/social_sharing', locals: { resource: @resource, cl: 'u-margin-top--base' } %>
          </div>
          <div class="o-resource-summary__content">
            <div class="o-resource__item o-resource__item--description">
              <h3>Description</h3>
              <%= @resource.description.try(:html_safe) %>
            </div>
            <%= render partial: 'resources/downloads', locals: { resource: @resource } %>
            <%= render partial: 'resources/prerequisites_standards', locals: { resource: @resource } %>
            <%= render partial: 'resources/bilingual_standards', locals: { resource: @resource, standards: @resource.bilingual_standards, color_code: color_code(@resource, base: true) } %>
            <%= render_tag_clouds(@resource) %>
            <% if @resource.engageny_url %>
            <div class="o-resource__item  o-resource__item--credits">
              <h3>Credits</h3>
              <%= render partial: 'resources/engageny', locals: { resource: @resource, color_code: color_code(@resource) } %>
            </div>
            <% end %>
          </div>
        </div>
        <% unless @resource.lesson? %>
          <div class="o-resource-summary--2x u-pd-content--xlarge cs-tint-bg--<%= color_code(@resource) %> u-br-bottom--base">
            <div class="o-resource-summary__map o-resource-summary__map--2x"></div>
            <div class="o-resource-summary__content--2x">
              <%= render partial: 'resources/children_list', locals: { resource: @resource, color_code: color_code(@resource, base: true) } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= render partial: 'resources/download_form', locals: { resource: @resource } %>
  </div>
  <div class="o-page__sticky">
    <div class="o-sticky o-sticky--right <%= 'o-sticky--disabled' unless @resource.next %>">
      <a class="o-sticky__btn o-sticky--right__btn" href="<%= @resource.next ? show_with_slug_path(@resource.next.slug) : '#' %>">
        <div class="o-page__wrap--row o-sticky__wrap o-sticky__wrap--right">
          <% if  @resource.next %>
            <div class="o-sticky__txt hide-for-small-only">
              <div class="o-sticky__arrow-subheader"><%= t('resources.btn.arrow', dir: 'Next', type: type_name(@resource.next)) %></div>
              <div class="o-sticky__arrow-header"><%= @resource.next.title %></div>
            </div>
          <% end %>
          <div class="o-sticky__txt show-for-small-only <%= 'u-link--disabled' unless @resource.next %>">
            <div class="o-sticky__arrow-subheader"><%= t('resources.btn.arrow-small', dir: 'Next', type: type_name(@resource)) %></div>
            <div class="o-sticky__arrow-header"><%= t('resources.btn.arrow-txt-small') %></div>
          </div>
          <div class="o-sticky__icon <%= 'u-link--disabled' unless @resource.next %>">
            <i class="fa-3x ub-angle-right"></i>
          </div>
        </div>
      </a>
    </div>
  </div>
</div>
<div id="related-instruction" class="u-bg--light">
  <div class="o-page">
     <%= react_component('RelatedInstruction',
                        { id: @resource.id,
                          resource_type: @resource.curriculum_type,
                          has_more: @related_instructions.has_more,
                          instructions: @related_instructions.instructions },
                          prerender: true) %>
  </div>
</div>