config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/' => 'welcome#index'

  get '/404'          => 'pages#not_found'
  # get '/about'        => 'pages#show_slug', slug: 'about'
  # get '/about/people' => 'pages#show_slug', slug: 'about_people'
  get '/tos'          => 'pages#show_slug', slug: 'tos',     as: :tos_page
  get '/privacy'      => 'pages#show_slug', slug: 'privacy', as: :privacy_page
  # get '/leadership'   => 'pages#leadership'
  get '/forthcoming'  => 'pages#forthcoming'

  get '/search' => 'search#index'

  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'

  resources :downloads, only: [:show] do
    member do
      get :preview
    end
  end
  get '/downloads/:id/pdf_proxy(/:s3)',
      as: :pdf_proxy_download, to: 'downloads#pdf_proxy', constraints: { s3: %r{[^\/]+} }
  get '/downloads/content_guides/:id(/:slug)', as: :content_guide_pdf, to: 'content_guides#show_pdf'
  resources :explore_curriculum, only: %i(index show)
  resources :enhance_instruction, only: :index
  resources :find_lessons, only: :index
  resources :pages, only: :show
  resources :resources, only: :show do
    get :pdf_proxy, on: :collection, path: 'pdf-proxy'
  end
  resource :survey, only: %i(create show)

  get '/resources/:id/related_instruction' => 'resources#related_instruction', as: :related_instruction
  get '/media/:id' => 'resources#media', as: :media
  get '/other/:id' => 'resources#generic', as: :generic
  get '/content_guides/:id(/:slug)', as: :content_guide, to: 'content_guides#show'

  resources :documents, only: :show do
    member do
      post 'export', to: 'documents#export'
      get 'export/status', to: 'documents#export_status'
      post 'lti', to: 'documents#show_lti'
    end
  end
  resources :materials, only: :show do
    member do
      get 'preview/pdf', to: 'materials#preview_pdf'
      get 'preview/gdoc', to: 'materials#preview_gdoc'
    end
  end

  devise_for :users, class_name: 'User', controllers: { registrations: 'registrations', sessions: 'sessions' }

  authenticate :user do
    mount Resque::Server, at: '/queue'
  end

  namespace :admin do
    get '/' => 'welcome#index'
    get 'google_oauth2_callback' => 'google_oauth2#callback'
    get '/association_picker' => 'association_picker#index'
    resources :content_guide_definitions, only: %i(index new) do
      get :import, on: :collection
    end
    resources :content_guides, except: :create do
      collection do
        get :import
        get :links_validation
        post :reset_pdfs
      end
    end
    resources :reading_assignment_texts
    resource :resource_bulk_edits, only: %i(new create)
    get '/resource_picker' => 'resource_picker#index'
    resources :resources, except: :show do
      member do
        post :export_to_lti_cc, path: 'export-lti-cc'
        post :unit_bundle
      end
    end
    resources :download_categories, except: :show
    resources :pages, except: :show
    resources :settings, only: [] do
      patch :toggle_editing_enabled, on: :collection
    end
    resources :staff_members, except: :show
    resources :users, except: :show do
      post :reset_password, on: :member
    end
    resources :leadership_posts, except: :show
    resources :content_guide_faqs, except: :show
    resources :standards, only: %i(index edit update)

    resources :components, only: %i(index show)
    resource :sketch_compiler, path: 'sketch-compiler', only: [] do
      get '/', to: 'sketch_compilers#new', defaults: { version: 'v1' }
      get '/:version/new', to: 'sketch_compilers#new', as: :new
      post '/:version/compile', to: 'sketch_compilers#compile', as: :compile
    end
    resources :documents, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'documents#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'documents#import_status'
      end
    end
    resources :materials, except: %i(edit show update) do
      collection do
        delete :delete_selected, to: 'materials#destroy_selected'
        post :reimport_selected
        get :import_status, to: 'materials#import_status'
      end
    end
    resources :documents, only: %i(index create new destroy)
    resources :materials, only: %i(index create new destroy)
    resource :curriculum, only: %i(edit update)
    resources :access_codes
    resource :batch_reimport, only: %i(new create)
  end

  get '/*slug' => 'resources#show', as: :show_with_slug
end

app/models/content_guide_faq.rb
class ContentGuideFaq < ActiveRecord::Base
  validates :title, :description, :subject, :heading, :subheading, presence: true
  validates :subject, uniqueness: { scope: :active }

  scope :where_subject, ->(subject) { where(active: true).where(subject: subject) }
end

app/controllers/admin/content_guide_faqs_controller.rb
module Admin
  class ContentGuideFaqsController < AdminController
    before_action :load_resource, only: %i(edit update destroy)

    def index
      @content_guide_faqs = ContentGuideFaq.all
    end

    def new
      @content_guide_faq = ContentGuideFaq.new
    end

    def create
      @content_guide_faq = ContentGuideFaq.new(content_guide_faq_params)

      if @content_guide_faq.save
        redirect_to :admin_content_guide_faqs, notice: t('.success')
      else
        render :new
      end
    end

    def edit; end

    def update
      if @content_guide_faq.update_attributes(content_guide_faq_params)
        redirect_to :admin_content_guide_faqs, notice: t('.success')
      else
        render :edit
      end
    end

    def destroy
      @content_guide_faq.destroy
      redirect_to :admin_content_guide_faqs, notice: t('.success')
    end

    private

    def load_resource
      @content_guide_faq = ContentGuideFaq.find(params[:id])
    end

    def content_guide_faq_params
      params
        .require(:content_guide_faq)
        .permit(:title, :subject, :active, :description, :heading, :subheading)
    end
  end
end

app/views/admin/content_guide_faqs/_form.html.erb
<% url = @content_guide_faq.new_record? ? :admin_content_guide_faqs : admin_content_guide_faq_url(@content_guide_faq) %>

<%= simple_form_for @content_guide_faq, url: url do |f| %>
  <%= f.input :title %>
  <%= f.input :subject, as: :select, collection: ['ela', 'math', 'lead'], include_blank: false %>
  <%= f.input :active %>
  <%= f.input :heading %>
  <%= f.input :subheading, as: :text, input_html: { rows: 2 } %>
  <%= f.input :description, as: :ckeditor, input_html: { rows: 10 } %>
  <br />
  <%= f.button :submit, t('ui.save'), name: nil %>
<% end %>

app/views/admin/content_guide_faqs/edit.html.erb
<% set_page_title @content_guide_faq.title %>

<div class=o-page>
  <h2 class=text-center><%= @content_guide_faq.title %></h2>

  <%= render 'form' %>
</div>

app/views/admin/content_guide_faqs/index.html.erb
<div class=o-page>
  <div class=clearfix>
    <div class=pull-right>
      <%= link_to t('.new_content_guide_faq'), :new_admin_content_guide_faq, class: 'btn btn-success' %>
    </div>
  </div>

  <h2 class=text-center><%= t('.page_title') %></h2>

  <table class=table>
    <tr>
      <th>ID
      <th><%= ContentGuideFaq.human_attribute_name :title %>
      <th><%= ContentGuideFaq.human_attribute_name :subject %>
      <th><%= ContentGuideFaq.human_attribute_name :active %>
      <th><%= t('ui.actions') %>
    </tr>

    <% @content_guide_faqs.each do |faq| %>
      <tr id=cg_faq_<%= faq.id %>>
        <td><%= faq.id %>
        <td><%= link_to faq.title, edit_admin_content_guide_faq_url(faq) %>
        <td><%= faq.subject %>
        <td><%= faq.active %>
        <td>
          <%= link_to t('ui.edit'), edit_admin_content_guide_faq_url(faq), class: 'btn btn-default' %>
          <%= button_to t('ui.delete'), admin_content_guide_faq_url(faq), class: 'btn btn-danger', data: { confirm: t('ui.are_you_sure') }, form_class: 'inline', method: :delete %>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/content_guide_faqs/new.html.erb
<div class=o-page>
  <h2 class=text-center><%= t('.page_title') %></h2>

  <%= render 'form' %>
</div>